[workspace]
resolver = "2"
members = [
    "shared",
    "agents/bank",
    "deploy",
]


[bank.metadata.lambda.watch.router]
"/get-balance/uuid/{uuid}" = [ 
    { method = "GET", function = "get-product" }
]
"/create-account" = [ 
    { method = "POST", function = "create-account" }
]