name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            target: aarch64-unknown-linux-gnu
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - name: Change directory to the workspace
        run: cd agents
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        run: cargo fmt
        working-directory: agents
      - name: Run cargo clippy
        working-directory: agents
        run: cargo clippy
      - name: Test
        working-directory: agents
        run: cargo test --lib --bins
        